# 服务配置
[server]
    name    = "bazaar"
    version = "1.0.0"
    address = "0.0.0.0:18528"

# 日志配置
[logger]
    # 日志等级
    level = "info"
    # 指定日志文件在滚动之前的最大大小 (单位:MB)
    max-size = 100
    # 保留日志文件的最大天数 (单位:天)
    max-age = 15
    # 最多滚动备份的文件数量
    max-backups = 15
    # 日志文件存储位置
    output = "log"
    # 是否在控制台标准输出
    stdout = true

# 样本文件存储配置
[storage]
    root-path = "/home/samples/06_bazaar"
    seek-file = "seek"

# 样本信息存储数据库
[database]
    server      = "127.0.0.1"
    username    = "admin"
    password    = "123456"
    bucket-name = "malware"

[scan-kit]

    [yara]
        address   = ":6141"
