// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: api/proto/yara.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestBlob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Blob []byte `protobuf:"bytes,1,opt,name=blob,proto3" json:"blob,omitempty"`
}

func (x *RequestBlob) Reset() {
	*x = RequestBlob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_yara_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestBlob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestBlob) ProtoMessage() {}

func (x *RequestBlob) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_yara_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestBlob.ProtoReflect.Descriptor instead.
func (*RequestBlob) Descriptor() ([]byte, []int) {
	return file_api_proto_yara_proto_rawDescGZIP(), []int{0}
}

func (x *RequestBlob) GetBlob() []byte {
	if x != nil {
		return x.Blob
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_yara_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_yara_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_api_proto_yara_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type Match struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rulename    string `protobuf:"bytes,1,opt,name=rulename,proto3" json:"rulename,omitempty"`
	Author      string `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Tags        string `protobuf:"bytes,3,opt,name=tags,proto3" json:"tags,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Match) Reset() {
	*x = Match{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_yara_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match) ProtoMessage() {}

func (x *Match) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_yara_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match.ProtoReflect.Descriptor instead.
func (*Match) Descriptor() ([]byte, []int) {
	return file_api_proto_yara_proto_rawDescGZIP(), []int{2}
}

func (x *Match) GetRulename() string {
	if x != nil {
		return x.Rulename
	}
	return ""
}

func (x *Match) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Match) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *Match) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File    string   `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Hit     bool     `protobuf:"varint,2,opt,name=hit,proto3" json:"hit,omitempty"`
	Matches []*Match `protobuf:"bytes,3,rep,name=matches,proto3" json:"matches,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_yara_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_yara_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_api_proto_yara_proto_rawDescGZIP(), []int{3}
}

func (x *Result) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Result) GetHit() bool {
	if x != nil {
		return x.Hit
	}
	return false
}

func (x *Result) GetMatches() []*Match {
	if x != nil {
		return x.Matches
	}
	return nil
}

type ScanFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *Result `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ScanFileResponse) Reset() {
	*x = ScanFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_yara_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanFileResponse) ProtoMessage() {}

func (x *ScanFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_yara_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanFileResponse.ProtoReflect.Descriptor instead.
func (*ScanFileResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_yara_proto_rawDescGZIP(), []int{4}
}

func (x *ScanFileResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type ScanFolderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result []*Result `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
}

func (x *ScanFolderResponse) Reset() {
	*x = ScanFolderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_yara_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanFolderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanFolderResponse) ProtoMessage() {}

func (x *ScanFolderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_yara_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanFolderResponse.ProtoReflect.Descriptor instead.
func (*ScanFolderResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_yara_proto_rawDescGZIP(), []int{5}
}

func (x *ScanFolderResponse) GetResult() []*Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_yara_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_yara_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_proto_yara_proto_rawDescGZIP(), []int{6}
}

var File_api_proto_yara_proto protoreflect.FileDescriptor

var file_api_proto_yara_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x79, 0x61, 0x72, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x79, 0x61, 0x72, 0x61, 0x22, 0x21, 0x0a, 0x0b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x6c, 0x6f, 0x62, 0x12, 0x12, 0x0a, 0x04, 0x62,
	0x6c, 0x6f, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6c, 0x6f, 0x62, 0x22,
	0x1d, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x71,
	0x0a, 0x05, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x75, 0x6c, 0x65, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x75, 0x6c, 0x65, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x61, 0x67, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x55, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x66,
	0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x68, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x68, 0x69,
	0x74, 0x12, 0x25, 0x0a, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x79, 0x61, 0x72, 0x61, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52,
	0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x22, 0x38, 0x0a, 0x10, 0x53, 0x63, 0x61, 0x6e,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x79,
	0x61, 0x72, 0x61, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x22, 0x3a, 0x0a, 0x12, 0x53, 0x63, 0x61, 0x6e, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x79, 0x61, 0x72, 0x61, 0x2e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x07,
	0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0xdc, 0x01, 0x0a, 0x0b, 0x59, 0x61, 0x72, 0x61,
	0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x33, 0x0a, 0x08, 0x53, 0x63, 0x61, 0x6e, 0x46,
	0x69, 0x6c, 0x65, 0x12, 0x0d, 0x2e, 0x79, 0x61, 0x72, 0x61, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x79, 0x61, 0x72, 0x61, 0x2e, 0x53, 0x63, 0x61, 0x6e, 0x46, 0x69,
	0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x0a,
	0x53, 0x63, 0x61, 0x6e, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x12, 0x0d, 0x2e, 0x79, 0x61, 0x72,
	0x61, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x79, 0x61, 0x72, 0x61,
	0x2e, 0x53, 0x63, 0x61, 0x6e, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x24, 0x0a, 0x06, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x12,
	0x0b, 0x2e, 0x79, 0x61, 0x72, 0x61, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0b, 0x2e, 0x79,
	0x61, 0x72, 0x61, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x08, 0x53,
	0x63, 0x61, 0x6e, 0x42, 0x6c, 0x6f, 0x62, 0x12, 0x11, 0x2e, 0x79, 0x61, 0x72, 0x61, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x6c, 0x6f, 0x62, 0x1a, 0x16, 0x2e, 0x79, 0x61, 0x72,
	0x61, 0x2e, 0x53, 0x63, 0x61, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x42, 0x0b, 0x5a, 0x09, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_yara_proto_rawDescOnce sync.Once
	file_api_proto_yara_proto_rawDescData = file_api_proto_yara_proto_rawDesc
)

func file_api_proto_yara_proto_rawDescGZIP() []byte {
	file_api_proto_yara_proto_rawDescOnce.Do(func() {
		file_api_proto_yara_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_yara_proto_rawDescData)
	})
	return file_api_proto_yara_proto_rawDescData
}

var file_api_proto_yara_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_yara_proto_goTypes = []interface{}{
	(*RequestBlob)(nil),        // 0: yara.RequestBlob
	(*Request)(nil),            // 1: yara.Request
	(*Match)(nil),              // 2: yara.Match
	(*Result)(nil),             // 3: yara.Result
	(*ScanFileResponse)(nil),   // 4: yara.ScanFileResponse
	(*ScanFolderResponse)(nil), // 5: yara.ScanFolderResponse
	(*Empty)(nil),              // 6: yara.Empty
}
var file_api_proto_yara_proto_depIdxs = []int32{
	2, // 0: yara.Result.matches:type_name -> yara.Match
	3, // 1: yara.ScanFileResponse.result:type_name -> yara.Result
	3, // 2: yara.ScanFolderResponse.result:type_name -> yara.Result
	1, // 3: yara.YaraScanner.ScanFile:input_type -> yara.Request
	1, // 4: yara.YaraScanner.ScanFolder:input_type -> yara.Request
	6, // 5: yara.YaraScanner.Reload:input_type -> yara.Empty
	0, // 6: yara.YaraScanner.ScanBlob:input_type -> yara.RequestBlob
	4, // 7: yara.YaraScanner.ScanFile:output_type -> yara.ScanFileResponse
	5, // 8: yara.YaraScanner.ScanFolder:output_type -> yara.ScanFolderResponse
	6, // 9: yara.YaraScanner.Reload:output_type -> yara.Empty
	4, // 10: yara.YaraScanner.ScanBlob:output_type -> yara.ScanFileResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_yara_proto_init() }
func file_api_proto_yara_proto_init() {
	if File_api_proto_yara_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_yara_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestBlob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_yara_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_yara_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Match); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_yara_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_yara_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_yara_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanFolderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_yara_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_yara_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_yara_proto_goTypes,
		DependencyIndexes: file_api_proto_yara_proto_depIdxs,
		MessageInfos:      file_api_proto_yara_proto_msgTypes,
	}.Build()
	File_api_proto_yara_proto = out.File
	file_api_proto_yara_proto_rawDesc = nil
	file_api_proto_yara_proto_goTypes = nil
	file_api_proto_yara_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// YaraScannerClient is the client API for YaraScanner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type YaraScannerClient interface {
	ScanFile(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ScanFileResponse, error)
	ScanFolder(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ScanFolderResponse, error)
	Reload(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	ScanBlob(ctx context.Context, opts ...grpc.CallOption) (YaraScanner_ScanBlobClient, error)
}

type yaraScannerClient struct {
	cc grpc.ClientConnInterface
}

func NewYaraScannerClient(cc grpc.ClientConnInterface) YaraScannerClient {
	return &yaraScannerClient{cc}
}

func (c *yaraScannerClient) ScanFile(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ScanFileResponse, error) {
	out := new(ScanFileResponse)
	err := c.cc.Invoke(ctx, "/yara.YaraScanner/ScanFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yaraScannerClient) ScanFolder(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ScanFolderResponse, error) {
	out := new(ScanFolderResponse)
	err := c.cc.Invoke(ctx, "/yara.YaraScanner/ScanFolder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yaraScannerClient) Reload(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/yara.YaraScanner/Reload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yaraScannerClient) ScanBlob(ctx context.Context, opts ...grpc.CallOption) (YaraScanner_ScanBlobClient, error) {
	stream, err := c.cc.NewStream(ctx, &_YaraScanner_serviceDesc.Streams[0], "/yara.YaraScanner/ScanBlob", opts...)
	if err != nil {
		return nil, err
	}
	x := &yaraScannerScanBlobClient{stream}
	return x, nil
}

type YaraScanner_ScanBlobClient interface {
	Send(*RequestBlob) error
	CloseAndRecv() (*ScanFileResponse, error)
	grpc.ClientStream
}

type yaraScannerScanBlobClient struct {
	grpc.ClientStream
}

func (x *yaraScannerScanBlobClient) Send(m *RequestBlob) error {
	return x.ClientStream.SendMsg(m)
}

func (x *yaraScannerScanBlobClient) CloseAndRecv() (*ScanFileResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ScanFileResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// YaraScannerServer is the server API for YaraScanner service.
type YaraScannerServer interface {
	ScanFile(context.Context, *Request) (*ScanFileResponse, error)
	ScanFolder(context.Context, *Request) (*ScanFolderResponse, error)
	Reload(context.Context, *Empty) (*Empty, error)
	ScanBlob(YaraScanner_ScanBlobServer) error
}

// UnimplementedYaraScannerServer can be embedded to have forward compatible implementations.
type UnimplementedYaraScannerServer struct {
}

func (*UnimplementedYaraScannerServer) ScanFile(context.Context, *Request) (*ScanFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScanFile not implemented")
}
func (*UnimplementedYaraScannerServer) ScanFolder(context.Context, *Request) (*ScanFolderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScanFolder not implemented")
}
func (*UnimplementedYaraScannerServer) Reload(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reload not implemented")
}
func (*UnimplementedYaraScannerServer) ScanBlob(YaraScanner_ScanBlobServer) error {
	return status.Errorf(codes.Unimplemented, "method ScanBlob not implemented")
}

func RegisterYaraScannerServer(s *grpc.Server, srv YaraScannerServer) {
	s.RegisterService(&_YaraScanner_serviceDesc, srv)
}

func _YaraScanner_ScanFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YaraScannerServer).ScanFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/yara.YaraScanner/ScanFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YaraScannerServer).ScanFile(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _YaraScanner_ScanFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YaraScannerServer).ScanFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/yara.YaraScanner/ScanFolder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YaraScannerServer).ScanFolder(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _YaraScanner_Reload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YaraScannerServer).Reload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/yara.YaraScanner/Reload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YaraScannerServer).Reload(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _YaraScanner_ScanBlob_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(YaraScannerServer).ScanBlob(&yaraScannerScanBlobServer{stream})
}

type YaraScanner_ScanBlobServer interface {
	SendAndClose(*ScanFileResponse) error
	Recv() (*RequestBlob, error)
	grpc.ServerStream
}

type yaraScannerScanBlobServer struct {
	grpc.ServerStream
}

func (x *yaraScannerScanBlobServer) SendAndClose(m *ScanFileResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *yaraScannerScanBlobServer) Recv() (*RequestBlob, error) {
	m := new(RequestBlob)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _YaraScanner_serviceDesc = grpc.ServiceDesc{
	ServiceName: "yara.YaraScanner",
	HandlerType: (*YaraScannerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScanFile",
			Handler:    _YaraScanner_ScanFile_Handler,
		},
		{
			MethodName: "ScanFolder",
			Handler:    _YaraScanner_ScanFolder_Handler,
		},
		{
			MethodName: "Reload",
			Handler:    _YaraScanner_Reload_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ScanBlob",
			Handler:       _YaraScanner_ScanBlob_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/yara.proto",
}
